package src.main.resources;
public enum Genero {
    ROCK, POP, MPB, SERTANEJO, FUNK, RAP, REGGAE, JAZZ, BLUES, CLASSICA, ELETRONICA,
    SAMBA, PAGODE, FORRO, AXE, BREGA, GOSPEL, INFANTIL, INDIE, COUNTRY, METAL, PUNK,
    ALTERNATIVO, HIPHOP, RNB, SOUL, FOLK, REGGAETON, KPOP, TRAP, LOFI, INSTRUMENTAL, SYNTHPOP
}
